spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      repositories:
        type: auto
      database: test
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG